/* ---------------------------------------------------- */
/*  Generated by Enterprise Architect Version 14.1 		*/
/*  Created On : 14-kvì-2020 16:28:17 				*/
/*  DBMS       : PostgreSQL 						*/
/* ---------------------------------------------------- */

/* Drop Tables */

DROP TABLE IF EXISTS "Account_Dimension" CASCADE
;

DROP TABLE IF EXISTS "Client_Dimension" CASCADE
;

DROP TABLE IF EXISTS "Credit_Card_Dimension" CASCADE
;

DROP TABLE IF EXISTS "Datamart_Facts" CASCADE
;

DROP TABLE IF EXISTS "District_Dimension" CASCADE
;

DROP TABLE IF EXISTS "Permanent_Order_Dimension" CASCADE
;

DROP TABLE IF EXISTS "Transaction_Dimension" CASCADE
;

/* Create Tables */

CREATE TABLE "Account_Dimension"
(
	account_pk bigint NOT NULL,
	frequency varchar(20) NULL,
	date date NULL,
	district_id bigint NULL
)
;

CREATE TABLE "Client_Dimension"
(
	client_pk bigint NOT NULL,
	birth_number varchar(6) NULL,
	district_id bigint NULL
)
;

CREATE TABLE "Credit_Card_Dimension"
(
	card_pk bigint NOT NULL,
	type varchar(20) NULL,
	issued date NULL
)
;

CREATE TABLE "Datamart_Facts"
(
	fact_pk bigint NOT NULL,
	account_fk bigint NULL,
	client_fk bigint NULL,
	card_fk bigint NULL,
	order_fk bigint NULL,
	trans_fk bigint NULL,
	district_fk bigint NULL,
	total_amount bigint NULL,
	total_paid_finished integer NULL,
	total_unpaid_finished integer NULL,
	total_paid_unfinished integer NULL,
	total_unpaid_unfinished integer NULL
)
;

CREATE TABLE "District_Dimension"
(
	district_pk bigint NOT NULL,
	district_name varchar(20) NULL,
	region varchar(20) NULL,
	inhabitants integer NULL,
	municipalities1 integer NULL,
	municipalities2 integer NULL,
	municipalities3 integer NULL,
	municipalities4 integer NULL,
	cities integer NULL,
	ratio_of_urban double precision NULL,
	salary integer NULL,
	unemployment95 double precision NULL,
	unemployment96 double precision NULL,
	enterpreneurs integer NULL,
	crimes95 integer NULL,
	crimes96 integer NULL
)
;

CREATE TABLE "Permanent_Order_Dimension"
(
	order_pk bigint NOT NULL,
	bank_to varchar(2) NULL,
	account_to varchar(50) NULL,
	amount double precision NULL,
	k_symbol varchar(20) NULL
)
;

CREATE TABLE "Transaction_Dimension"
(
	trans_pk bigint NOT NULL,
	date date NULL,
	type varchar(20) NULL,
	operation varchar(20) NULL,
	amount double precision NULL,
	balance double precision NULL,
	k_symbol varchar(20) NULL,
	bank varchar(2) NULL,
	account varchar(50) NULL
)
;

/* Create Primary Keys, Indexes, Uniques, Checks */

ALTER TABLE "Account_Dimension" ADD CONSTRAINT "PK_Account_Dimension"
	PRIMARY KEY (account_pk)
;

ALTER TABLE "Client_Dimension" ADD CONSTRAINT "PK_Client_Dimension"
	PRIMARY KEY (client_pk)
;

ALTER TABLE "Credit_Card_Dimension" ADD CONSTRAINT "PK_Credit_Card_Dimension"
	PRIMARY KEY (card_pk)
;

ALTER TABLE "Datamart_Facts" ADD CONSTRAINT "PK_Datamart_Facts"
	PRIMARY KEY (fact_pk)
;

CREATE INDEX "IXFK_Datamart_Facts_Account_Dimension" ON "Datamart_Facts" (account_fk ASC)
;

CREATE INDEX "IXFK_Datamart_Facts_Client_Dimension" ON "Datamart_Facts" (client_fk ASC)
;

CREATE INDEX "IXFK_Datamart_Facts_Credit_Card_Dimension" ON "Datamart_Facts" (card_fk ASC)
;

CREATE INDEX "IXFK_Datamart_Facts_District_Dimension" ON "Datamart_Facts" (district_fk ASC)
;

CREATE INDEX "IXFK_Datamart_Facts_Permanent_Order_Dimension" ON "Datamart_Facts" (order_fk ASC)
;

CREATE INDEX "IXFK_Datamart_Facts_Transaction_Dimension" ON "Datamart_Facts" (trans_fk ASC)
;

ALTER TABLE "District_Dimension" ADD CONSTRAINT "PK_District_Dimension"
	PRIMARY KEY (district_pk)
;

ALTER TABLE "Permanent_Order_Dimension" ADD CONSTRAINT "PK_Permanent_Order_Dimension"
	PRIMARY KEY (order_pk)
;

ALTER TABLE "Transaction_Dimension" ADD CONSTRAINT "PK_Transaction_Dimension"
	PRIMARY KEY (trans_pk)
;

/* Create Foreign Key Constraints */

ALTER TABLE "Datamart_Facts" ADD CONSTRAINT account_fk
	FOREIGN KEY (account_fk) REFERENCES "Account_Dimension" (account_pk) ON DELETE No Action ON UPDATE No Action
;

ALTER TABLE "Datamart_Facts" ADD CONSTRAINT card_fk
	FOREIGN KEY (card_fk) REFERENCES "Credit_Card_Dimension" (card_pk) ON DELETE No Action ON UPDATE No Action
;

ALTER TABLE "Datamart_Facts" ADD CONSTRAINT client_fk
	FOREIGN KEY (client_fk) REFERENCES "Client_Dimension" (client_pk) ON DELETE No Action ON UPDATE No Action
;

ALTER TABLE "Datamart_Facts" ADD CONSTRAINT district_fk
	FOREIGN KEY (district_fk) REFERENCES "District_Dimension" (district_pk) ON DELETE No Action ON UPDATE No Action
;

ALTER TABLE "Datamart_Facts" ADD CONSTRAINT order_fk
	FOREIGN KEY (order_fk) REFERENCES "Permanent_Order_Dimension" (order_pk) ON DELETE No Action ON UPDATE No Action
;

ALTER TABLE "Datamart_Facts" ADD CONSTRAINT transaction_fk
	FOREIGN KEY (trans_fk) REFERENCES "Transaction_Dimension" (trans_pk) ON DELETE No Action ON UPDATE No Action
;
